Add Web Authentication API demo to the Test Drive Demos
MicrosoftEdge/Demos-old pull request #163
Opened 2016-10-12 16:33 UTC by AngeloKai

The live demo is [here](https://fidodemo2.azurewebsites.net/webauthn/) The code implements a polyfill (webauthn.js) to bridge the gap between the new Web Authentication API and the preliminary Microsoft implementation. It also showcases a demo website which demonstrates how the register and logon flow looks like when using the new API. The current codebase only implements the client-side code. The public keys generated by the WebAuthN API are typically sent to the server but, in this codebase, only stored in indexedDB. 
All images and libraries used here are either free or under Apache 2.0 license.

2016-10-20 18:22 UTC, molant requested changes
@melanierichards can you please take a look at this PR? There are some things with the HTML and CSS that you might want to review.

Thanks!

2016-10-20 18:22 UTC, molant commented on webauthn/.idea/jsLibraryMappings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Add `.idea` to a `.gitignore` file so all these unnecessary files aren't uploaded

2016-10-20 18:22 UTC, molant commented on webauthn/inbox.html
> +<meta name="GENERATOR" content="MSHTML 11.00.10537.1000">
Remove this line

2016-10-20 18:22 UTC, molant commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="./css/style.css">
relative path. No need to put `./`

2016-10-20 18:22 UTC, molant commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
Is this file really needed? I think you are using custom styles for everything, right?
@melanierichards thoughts?

2016-10-20 18:22 UTC, molant commented on webauthn/index.html
> +    <meta name="GENERATOR" content="MSHTML 11.00.10537.1000">
Same comments as for `inbox.html` re GENERATOR and CSS.

2016-10-20 18:22 UTC, molant commented on webauthn/index.html
> +        <button class="reset-button" id="link-reset-session" onclick="resetPage()" style="display: inline;">Reset session</button>
Please don't put event handles in the html

2016-10-20 18:22 UTC, molant commented on webauthn/index.html
> +                                <button class="default" id="button-logon-with-windows-hello" style="display: none;">Sign In with Windows Hello</button>
Please no inline styles anywhere.

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/demo.js
> +		if (bool) {
I believe we should be using the `hide` attribute here (and in other places where we do similar things) and no styles for accessibility purposes

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/demo.js
> +		document.getElementById('input-password').style.display = 'block';
Refactor all the `style.display = 'block/none'` in a function adding and removing the `hide` attribute.

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/demo.js
> +			// We won't use this optional parameters
Detail this comment. If we are not going to use them why do we create them?

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/demo.js
> +		try {
This `try` is not needed. All the code that gets executed here is inside a promise.

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/demo.js
> +			// There is only one type defined in the spec.
Maybe link to the speck here?

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/demo.js
> +		location.href = 'inbox.html';
This is not consistent with the rest of the code. Sometimes you are doing `window.location = 'inbox.html'` and some others `location.href = 'inbox.html'`. Use the same always. Also this code is repeated several times and maybe `inbox.html` will be renamed so better to refactor and create a function `goToHome` or something similar that does that.

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/updateui.js
> +		document.getElementById('button-logon-with-password').style.display = 'none';
Same as before with `hide` and a11y

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/updateui.js
> +		document.getElementById('button-logon-with-password').style.display = 'none';
Also, aren't this functions the same as in the previous file?

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/updateui.js
> +					// If Windows Hello is supported, offer to register Windows Hello
Align comment with start of code in the next line

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/updateui.js
> +				// If the WebAuthN API is not supported, neglect the WebAuthN register
Align comment with code

2016-10-20 18:22 UTC, molant commented on webauthn/web.config
> +<system.webServer>
We don't need this file, it is specific for IIS. Also the quotes character is the wrong one (probably want to fix that in the production demo).

2016-10-20 18:22 UTC, molant commented on webauthn/.vscode/settings.json
> +    "eslint.autoFixOnSave": true
Add `.vscode` to the `.gitignore` file too

2016-10-20 18:22 UTC, molant commented on webauthn/scripts/updateui.js
> +(function () {
Why do we have a separate file instead of having everything in `demo.js`? There is code that can be shared and `updateui.js` isn't a very descriptive name.

2016-10-20 18:31 UTC, AngeloKai commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
I am not clear about that part. The css part was handled by @ststimac. I am not sure what is included in that file

2016-10-20 19:11 UTC, melanierichards commented on webauthn/index.html
> +            <div class="centerParent">
Would be good to commit to a class name style (you have camelCase and dash-separated). Hyphens are more in line with the "house style". camelCase for JS IDs is fine.

2016-10-20 19:11 UTC, melanierichards commented on webauthn/index.html
> +                                    <div class="errorDiv" id="idTd_PWD_ErrorMsg_Password"></div>
A few suggestions here:
- consider `.error` instead of `.errorDiv` so you can apply this to other elements
- Maybe this should be a `<p>` element anyway
- It's better to insert this error via JS instead of having an empty element on the page. But if you must have it in the markup, add `aria-hidden="true"` and remove the attribute if the element gets populated w/ content via JS.

2016-10-20 19:11 UTC, melanierichards commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
We'll probably have to wait for her feedback on that, then. She's back in tomorrow, I think. It seems like it might not be needed.

2016-10-20 19:11 UTC, melanierichards commented on webauthn/css/style_download.css
> +.skydrive a:active {
A lot of repeated styles here, could there be one shared class used as a hook for link styles? Or even a parent-based selector that targets each link that shares styles?

2016-10-20 19:11 UTC, melanierichards commented on webauthn/css/style_download.css
> +	margin: 0px; padding: 0px; line-height: 29px; font-family: "Segoe UI Web Light"; font-size: 31px; font-weight: 100;
Use relative units (rem/em) instead of px (this applies to other lines in the CSS as well)

2016-10-20 19:11 UTC, melanierichards commented on webauthn/css/style_download.css
> +	margin: 12px 0px 18px; padding: 0px; line-height: 16px; font-family: "Segoe UI Web Regular"; font-size: 14px; font-weight: 100;
No single-line CSS, please

2016-10-20 19:11 UTC, melanierichards commented on webauthn/css/style_download.css
> +div#offer {
Can you remove the element tag from this selector? (`div`)

2016-10-20 19:11 UTC, melanierichards commented on webauthn/css/style_download.css
> +	font-family: Segoe UI Web Light;
You can register all these weights of Segoe as "Segoe UI" and then just change the font-weight whenever you use them in the CSS, instead of having to declare the font-weight and change the font family. However, I'm unsure that @font-face is even needed here, as you're using all system fonts. Is the only thing you gain here the use of shorthand through the rest of the file?

2016-10-20 19:13 UTC, melanierichards commented
@AngeloKai my comments are in!

This doesn't apply to a particular line, but if you haven't already, test all the text and background color combos to make sure they pass a color contrast of 4.5:1 http://leaverou.github.io/contrast-ratio/

2016-10-20 20:05 UTC, ststimac commented
@melanierichards I'm back on Monday. I edited the CSS file very minimally. I can't remember if the demotemplate.css was needed or not. That was back at the end of June. I may have kept that in place because of the layout issues we had with the speech demo.

2016-10-20 20:53 UTC, AngeloKai commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
In some parts of the style.css, it mentions "override demo template" so I assume it have some usage. Let me try removing it to see what would happen.

2016-10-20 20:54 UTC, melanierichards commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
Or it may have no usage and it's just getting in the way :P

2016-10-20 21:20 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +		if (bool) {
I changed all of them to visibility: hidden in css. What do you mean "no styles for accessibility purposes"?

2016-10-20 21:35 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +		try {
My concern is if something goes wrong in retrieving or setting data in localStorage, a catch statement could help in that case.

2016-10-20 21:36 UTC, molant commented on webauthn/scripts/demo.js
> +		if (bool) {
What I meant is that you should use the attribute `hidden`, not `visibility: hidden`.
@melanierichards or @dstorey can give you more details about the reasoning.

2016-10-20 22:38 UTC, AngeloKai commented on webauthn/scripts/updateui.js
> +(function () {
My original concern was that too many functions would be stacked together in one file. The most important functions in the entire files are createCredential() and verify(). I will go ahead and merge them together. I will write some text in the beginning of demo.js to signal developers to pay attention to those two functions.

2016-10-24 16:43 UTC, ststimac commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
Let me know if you need me to hop in and update anything.

2016-10-25 21:23 UTC, AngeloKai commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
I removed the line and found the layout of the page becomes defunct. I am keeping the file for the demo.

2016-10-25 21:24 UTC, AngeloKai commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="./css/style.css">
Fixed.

2016-10-25 21:24 UTC, AngeloKai commented on webauthn/inbox.html
> +<meta name="GENERATOR" content="MSHTML 11.00.10537.1000">
Fixed.

2016-10-25 23:19 UTC, melanierichards commented
@AngeloKai this is the link I referred to for finding shades of a color: http://www.0to255.com. So if you were finding a shade of #ffcc00, you would do http://www.0to255.com/ffcc00

2016-10-26 02:28 UTC, AngeloKai commented on webauthn/index.html
> +    <meta name="GENERATOR" content="MSHTML 11.00.10537.1000">
Fixed.

2016-10-26 03:35 UTC, AngeloKai commented on webauthn/index.html
> +        <button class="reset-button" id="link-reset-session" onclick="resetPage()" style="display: inline;">Reset session</button>
Fixed.

2016-10-26 07:13 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +		if (bool) {
Refactoring from style.display to hidden is not useful here. Per HTML5.1 rule, any change to the display property will lead to the hidden attribute being overridden. The css blob file from edge sets the display property and renders the hidden attribute useless. In addition, the button needs to be set to block if needed to be shown. There is the possibility of setting display to none and then use hidden when an element no longer needs to be shown. When an element does need to be shown, the display is set to block. But I am not sure if that would violate the accessibility rules. 
In light of that finding, I will just create and remove element on the fly.

2016-10-26 20:22 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +		try {
I scoped the try statement to only the localStorage portion.

2016-10-26 20:26 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +			// We won't use this optional parameters
Expanded the comment as: In consistent with the general Javascript rule about dictionary, if a member is not needed, there is no need to specify it or give it a null value. For the sake of demonstration, rpId, allowList, and extensions are specified here.

2016-10-26 20:28 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +			// There is only one type defined in the spec.
Added

2016-10-26 20:30 UTC, AngeloKai commented on webauthn/scripts/demo.js
> +		location.href = 'inbox.html';
Refactored.

2016-10-26 20:32 UTC, AngeloKai commented on webauthn/scripts/updateui.js
> +(function () {
updateui.js is integrated into the demo.js file. It is deleted now.

2016-10-26 20:39 UTC, dstorey commented on webauthn/scripts/demo.js
> +		if (bool) {
hidden attribute and display: none; map to the same thing in UIA and other A11y APIs, so doesn't make a big difference which one is used, but the former is probably cleaner (no inline styles if that is how you're adding it) and more semantic (shows in the DOM that it is not in the tree).

2016-10-26 20:41 UTC, dstorey commented on webauthn/scripts/demo.js
> +		if (bool) {
I don't remember off the top of my head if visibility: hidden; is removed from the a11y tree like display: none is (there is no CSS AAM spec like there is for HTML AAM)

2016-10-26 21:47 UTC, AngeloKai commented on webauthn/css/style_download.css
> +	margin: 12px 0px 18px; padding: 0px; line-height: 16px; font-family: "Segoe UI Web Regular"; font-size: 14px; font-weight: 100;
Fixed

2016-10-26 21:48 UTC, AngeloKai commented on webauthn/css/style_download.css
> +div#offer {
The div turned out to be not useful. Removed the css selector instead.

2016-10-26 21:49 UTC, AngeloKai commented on webauthn/css/style_download.css
> +	margin: 0px; padding: 0px; line-height: 29px; font-family: "Segoe UI Web Light"; font-size: 31px; font-weight: 100;
Fixed.

2016-10-26 21:49 UTC, AngeloKai commented on webauthn/css/style_download.css
> +	font-family: Segoe UI Web Light;
Removed the entire style_download.css file

2016-10-26 22:09 UTC, ststimac commented on webauthn/inbox.html
> +<link rel="stylesheet" type="text/css" href="https://edgeportal.blob.core.windows.net/media/demotemplate.css">
The demotemplate.css file is still needed for layout, fonts, button styles...structural things. It was a part of the original file that I got from Rob.

2016-10-28 01:35 UTC, AngeloKai commented
@ststimac I changed allcolor in css to #da3838 but logo is a PS asset. I don't have PS on my work computer. Can you change the color of them and add the asset in? Thank you!

2016-10-28 15:49 UTC, ststimac commented
@AngeloKai I'll email you the new logo. I can't add SVGs here.

2016-10-28 17:58 UTC, molant commented
@AngeloKai you still have to ignore the .idea for this demo

2016-10-28 17:59 UTC, molant commented
Also, let's add a config.json file to this demo with 
```
{
  "isHtml": true
}
```

2016-10-28 18:03 UTC, AngeloKai commented
All the requested changes have been made. Please review @molant

2016-11-01 18:43 UTC, molant commented
@AngeloKai there are a few files I don't see where they are used:
* controls.png 
* golden-retriever.jpg

Also, where did you got the puppy-cam-login.jpg?

2016-11-01 19:14 UTC, AngeloKai commented
Sorry for the confusion. I will remove controls.png and golden-retriever.png. I got all of my assets from @ststimac . According to her, all assets for this demo comes from [pexels] (https://www.pexels.com/), a website for free stock photos.

2016-11-01 19:40 UTC, molant commented
OK, I've checked and it has a CC0 license so we are good. @AngeloKai can you squash?

2016-11-02 14:39 UTC, closed without merging