SVG Demo UI Update
MicrosoftEdge/Demos-old pull request #167
Opened 2016-10-26 21:20 UTC by ststimac

@molant @melanierichards this is ready for initial review at your leisure. There are a few items that I know will need to be removed. There are some inline styles for display: none; that directly tie to the JS file and I'm not sure what to edit. If I try and apply a class to the element, the action to show the element no longer works. 

There are also two "!important" rules that I want to remove and I'm sure they can be, it's just a matter of finding the correct bit in the Javascript to remove. Previously the buttons in the sidebar all had a preview of the gradient directions and it was overwhelming. The buttons as well need an active state, and I again think that is being controlled in the Javascript. 

Anton, the other thing I would like to do is separate out the hex code from the color swatch so that there are two different input options, either by color picker which populates the hex code, or if you enter the hex code it changes the color swatch. I tried and tried to get this to work correctly but was having difficulty with the adding that third column, and adding new rows as you add new color stops. 
I updated all the Javascript ids to camel case, and cleaned up the CSS too.

2016-10-27 13:57 UTC, molant requested changes
I think we are not going to waste time improving the old JS. As long as the demo looks better I'm fine with it. @melanierichards what do you think?
@ststimac uou also have to add a config.json file in the root:

```
{
  isHtml: true
}
```

so we don't have any problem with other styles.

Nice job!

2016-10-27 13:57 UTC, molant commented on svgradientbackgroundmaker/images/btn_delete.svg
> +			10.7,8.9 		"/>
Empty spaces here, have you run it through svggo?

2016-10-28 16:39 UTC, ststimac commented
@molant added the json file. 

I'm also fine with leaving everything the way it is (JavaScript wise) and not bothering with separating the hexcode and swatch.

2016-10-28 17:15 UTC, melanierichards commented
@ststimac whew this looks so much nicer now. Only comment is it doesn't seem like the Montserrat font is being loaded in the CSS, probably just your local copy (it's falling back to Arial on my machine). Besides fixing that, we might also want to put Segoe UI in the font stack after Montserrat.

2016-10-28 17:16 UTC, ststimac commented
OK, I'll check that and add Segoe UI.

2016-10-28 17:30 UTC, molant commented
@ststimac can you try adding the following after the rest of scripts?
```
<script type="text/javascript" src="https://msedgecdn.azurewebsites.net/scripts/demo-header.js"></script>
```

2016-10-28 18:29 UTC, ststimac commented
@molant that has been added.

2016-10-28 18:32 UTC, molant approved these changes

2016-10-28 18:32 UTC, merged