Make `a11y` related change for `eme` demo
MicrosoftEdge/Demos-old pull request #253
Opened 2016-12-16 10:52 UTC by alrra

This should fix: MicrosoftEdge/Demos/issues/241.

---

Changes:

* Use `<label>` instead of `<p>`.

* Add and sync `value` for `bitrateSlider`.

  > Another thing to note is the value should be kept in sync with the bitrate value after it. I'm skeptical this is the case as it has a max="7" applied to it, while bitrate goes up to 59999

    @dstorey The value basically [represents the level](https://github.com/MicrosoftEdge/Demos/blob/428c55490a2dc9144e0760a5d4651204bd9e6813/eme/scripts/demo.js#L768), and I made that sync. 

---

Notes: 
  
   * I haven't made any improvement, and respected the existing coding style .
   * haha @ [Not Your Father's Browser](https://vimeo.com/102845901)

2016-12-16 16:03 UTC, sarvaje requested changes

2016-12-16 16:03 UTC, sarvaje commented on eme/scripts/demo.js
> +
Remove this white line please.

2016-12-16 16:10 UTC, alrra commented on eme/scripts/demo.js
> +
@sarvaje Done!

2016-12-19 16:12 UTC, sarvaje approved these changes

2016-12-29 12:22 UTC, dstorey approved these changes

2016-12-29 12:22 UTC, merged