Add `button` to toggle music in `Let it snow` demo
MicrosoftEdge/Demos-old pull request #256
Opened 2016-12-19 13:40 UTC by alrra

Ref: MicrosoftEdge/Demos#210

<img src="https://cloud.githubusercontent.com/assets/1223565/21314706/266837e4-c601-11e6-846c-2f8d7211104b.png">

2016-12-19 16:06 UTC, sarvaje requested changes

2016-12-19 16:06 UTC, sarvaje commented on letitsnow/js/default.js
> +        var charCode = (typeof evt.which == "number") ? evt.which : evt.keyCode;
Use `===` instead of `==`

2016-12-19 16:06 UTC, sarvaje commented on letitsnow/js/default.js
> +         toggleSoundButton.innerHTML="Play music";
wrap the `=` symbol with white spaces

2016-12-19 16:06 UTC, sarvaje commented on letitsnow/js/default.js
> +         toggleSoundButton.innerHTML="Pause music";
wrap the `=` symbol with white spaces

2016-12-19 16:10 UTC, alrra commented on letitsnow/js/default.js
> +        var charCode = (typeof evt.which == "number") ? evt.which : evt.keyCode;
@sarvaje Changes made!

2016-12-20 23:17 UTC, sarvaje approved these changes
LGTM

2016-12-21 23:23 UTC, sarvaje commented
@melanierichards or @dstorey can you validate/merge this PR?

2016-12-28 22:49 UTC, melanierichards commented
Fantastico, merging.

2016-12-28 22:49 UTC, merged