Use `<button>` instead of `<div>` in `BetaFish` demo
MicrosoftEdge/Demos-old pull request #260
Opened 2016-12-21 15:47 UTC by alrra

Fix MicrosoftEdge/Demos#185.

2016-12-21 16:39 UTC, sarvaje requested changes

2016-12-21 16:39 UTC, sarvaje commented on betafish/Script/Settings.js
> +
remove this empty line please

2016-12-21 16:41 UTC, alrra commented on betafish/Script/Settings.js
> +
@sarvaje Done!

2016-12-21 16:42 UTC, sarvaje approved these changes

2016-12-21 16:42 UTC, sarvaje commented
LGTM

2016-12-21 23:23 UTC, sarvaje commented
@melanierichards or @dstorey can you validate/merge this PR?

2016-12-28 22:43 UTC, melanierichards commented
Shippin it!

2016-12-28 22:43 UTC, merged