Remove all gists from demos
MicrosoftEdge/Demos-old pull request #264
Opened 2016-12-21 22:35 UTC by melanierichards

Fixes #225

2016-12-21 23:42 UTC, molant commented
If I've understood correctly we are removing gift because they don't scale when we increase the size. It's that correct? Is this the only solution we can come up with? Is this a problem with the platform or with github?

2016-12-22 01:06 UTC, melanierichards commented
We wanted to get rid of them anyway. They're inconsistent with other code samples (`code` inside a `pre`) and why bother loading scripts just for code samples?

2016-12-29 12:16 UTC, dstorey requested changes
question about class and pointing out encoding issue for amps

2016-12-29 12:16 UTC, dstorey commented on webaudiotuner/index.html
> +	if(newBaseFreq >= 432 && newBaseFreq <= 446) {
amp Probably needs escaped here

2016-12-29 12:16 UTC, dstorey commented on webaudiotuner/index.html
> +			if(newNoteIndex >= 0 && newNoteIndex < notesArray.length) {
same here

2016-12-29 12:16 UTC, dstorey commented on webaudiotuner/index.html
> +	if((navigator.mediaDevices && navigator.mediaDevices.getUserMedia) || navigator.getUserMedia){
...and again

2016-12-29 12:16 UTC, dstorey commented on webaudiotuner/index.html
> +	var getUserMedia = navigator.mediaDevices && navigator.mediaDevices.getUserMedia ?
...and again

2016-12-29 12:16 UTC, dstorey commented on @supports/index.html
> +<pre><code class="css">b {
This and others in this file have class="css" but css in other files and the html and js ones don;t. are we using any library that hooks into the css class to add highlighting?

2017-01-05 01:20 UTC, melanierichards commented on @supports/index.html
> +<pre><code class="css">b {
Hrm. Maybe I did weird copy-pasting from elsewhere? Not sure, removing.

2017-01-05 01:41 UTC, melanierichards commented
@dstorey made the changes! This is ready to review again.

2017-01-05 08:37 UTC, dstorey approved these changes

2017-01-05 17:27 UTC, merged