Fixed focus on Audiomixer demo's popup
MicrosoftEdge/Demos-old pull request #275
Opened 2016-12-22 23:26 UTC by sarvaje

Fixed #205

2017-01-04 20:55 UTC, dstorey commented
As this is JS I'll leave for @alrra to review.

2017-01-05 17:26 UTC, molant requested changes

2017-01-05 17:26 UTC, molant commented on audiomixer/scripts/ui.js
> +		var array = [];
Can you replace this with:
```javascript
return [].slice.call(collection);
```

so we are consistent with the rest of the projects?

2017-01-05 17:52 UTC, sarvaje commented on audiomixer/scripts/ui.js
> +		var array = [];
@molant done!

2017-01-05 18:42 UTC, molant approved these changes

2017-01-05 18:42 UTC, merged