User Select Demo Cleanup
MicrosoftEdge/Demos-old pull request #304
Opened 2016-12-28 23:31 UTC by ststimac

New PR for the user select demo. This should be free of other demo conflicts & only be the user select files. 

@melanierichards

2016-12-29 11:53 UTC, dstorey requested changes

2016-12-29 11:53 UTC, dstorey commented on svgradientbackgroundmaker/index.html
> +	<article class="container">
White space needs removed

2016-12-29 11:53 UTC, dstorey commented on svgradientbackgroundmaker/index.html
> +	<article class="container">
...and .DS-Storey below. Wont let me comment on that

2016-12-29 11:53 UTC, dstorey commented on userselect/images/avatar_1.svg
> +<svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 34"><style>.st0{clip-path:url(#SVGID_2_);} .st1{fill:#D2D2D2;} .st2{fill:#4E4E4E;}</sty
Can you run this and the other svg through an optimiser to remove the unneeded id/class , etc? Lower case hex codes too (our linter doesn't pick them up in SVG :()

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +<section role="region "class="container section">
role attribute isn't needed anymore

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +		<select id="sel" class="controls-select">
looks like this select needs a label

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +-ms-user-select:none;
spaces between : and value

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +			<a href="#">MSDN Blogs</a> \
we may as well add the real href values here to avoid any potential a11y flags here

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +		<p class="date"><a href="#">ieblog</a> 31 Oct 2011 3:42 PM</p>
Same comment as above

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +				<img src="images/avatar_1.svg" class="avatar" alt="avatar" role="presentation" />
if this has role presentation then the alt attribute is not needed, as that removes from a11y tree. Role should be first attribute (in our style guide) as it should be close to the semantic that it is replacing (the start tag)

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +				<img src="images/avatar_1.svg" class="avatar" alt="avatar" role="presentation" />
Same comment as above

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +		<input type="text"><br/><br/>
needs label associated with input (id/for attributes)

2016-12-29 11:53 UTC, dstorey commented on userselect/index.html
> +<section role="region" class="container section">
role is not needed any longer here

2016-12-29 16:25 UTC, ststimac commented on userselect/images/avatar_1.svg
> +<svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 34"><style>.st0{clip-path:url(#SVGID_2_);} .st1{fill:#D2D2D2;} .st2{fill:#4E4E4E;}</sty
I ran them through one yesterday. I'll try again.

2016-12-29 16:49 UTC, ststimac commented on userselect/index.html
> +			<a href="#">MSDN Blogs</a> \
I'd rather just delete the links so people stay on the demo page.

2016-12-29 19:23 UTC, dstorey approved these changes

2017-01-06 02:36 UTC, melanierichards commented
Looks good!

2017-01-06 02:36 UTC, merged

2017-01-06 02:37 UTC, ststimac commented
Hooray! ?

Sent using OWA for iPhone
________________________________
From: Melanie Richards <notifications@github.com>
Sent: Thursday, January 5, 2017 6:36:32 PM
To: MicrosoftEdge/Demos
Cc: Stephanie Drescher; Author
Subject: Re: [MicrosoftEdge/Demos] User Select Demo Cleanup (#304)


Merged #304<https://github.com/MicrosoftEdge/Demos/pull/304>.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftEdge/Demos/pull/304#event-913560987>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ARPGK2FojbJCSVX1tcHf64znLiHT1If2ks5rPaiwgaJpZM4LXQTi>.