Custom props
MicrosoftEdge/Demos-old pull request #360
Opened 2017-03-17 20:56 UTC by gregwhitworth

## What this PR does

This PR brings int he 

## Requirements

* [ ] My PR follows all applicable accessibility requirements (See [`.github/ACCESSIBILITY_REQS.md`](https://github.com/MicrosoftEdge/Demos/blob/master/.github/ACCESSIBILITY_REQS.md)).

2017-03-18 03:05 UTC, molant commented
@melanierichards can you take a look at this demo?

2017-03-18 03:05 UTC, molant requested changes

2017-03-18 03:05 UTC, molant commented on custom-props/config.json
> +   "skip": true
Do we want to have this demo appear in the site? If so remove `"skip": true`

2017-03-18 03:05 UTC, molant commented on custom-props/index.html
> +                <?xml version="1.0" encoding="utf-8"?>
Do we need this here?

2017-03-18 03:05 UTC, molant commented on custom-props/index.html
> +                <svg id="container" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
Has this SVG been run through svg go or another optimizer?

2017-03-18 04:23 UTC, gregwhitworth commented on custom-props/index.html
> +                <svg id="container" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
No I haven't, just ran it and since it produces a giant block of minified paths I'm not going to commit that until I have a chance to test it on a current build internally.

2017-03-18 04:23 UTC, gregwhitworth commented on custom-props/index.html
> +                <?xml version="1.0" encoding="utf-8"?>
Nope, this is an artifact after moving the svg around, I've moved it to the correct location. Thanks.

2017-03-18 04:24 UTC, gregwhitworth commented on custom-props/config.json
> +   "skip": true
Yes, that said maybe we can have the demo go live with it not at first so we can link it up in the blog. Then turn it on later?

2017-03-18 05:31 UTC, molant commented on custom-props/config.json
> +   "skip": true
This property is to skip completely the processing of a folder like the example one or old demos from testdrive that we don't want to have in the site but we maintain in the repo. You want to remove this property and we can still decide when to make it public via the admin page.

2017-03-18 05:32 UTC, molant commented
We will need an image for the tile of this demo. Have you talked with @ststimac about it?

2017-03-18 18:56 UTC, gregwhitworth commented
@molant Nope haven't spoken with @ststimac about the tile. Stephanie do you mind creating one?

2017-03-20 19:40 UTC, ststimac commented
@gregwhitworth yes I can make a tile for this.

2017-03-20 20:14 UTC, ststimac commented
Here's a tile for EdgePortal. 
![custom_props_tile1](https://cloud.githubusercontent.com/assets/18073131/24119623/20a6a196-0d6f-11e7-84a9-64505395d9f2.jpg)

2017-03-20 21:59 UTC, gregwhitworth commented
@melanierichards this should be good for review from you

2017-03-20 22:34 UTC, melanierichards requested changes
Nice @gregwhitworth and @ststimac!

Comments that don't have a particular place inline:

* I can't seem to figure out where this is coming from, but when you first load the page, the background behind the "properties changed" code is light brown. I don't think that passes a 4.5:1 ratio with the white text.
* For a11y reasons I think we need to have some kind of control that will allow the person to pause all the animations in the SVG.
* Make the headings the semilight weight of Segoe (see my inline comment that has the weights of Segoe in a code snippet)
* Wherever possible, can you change the px margin values to em or rem?
* Another code preference thing we have which I believe is in a different repo and not here (which I should update), is CSS property order:

```
Display
Positioning
Box Model
Backgrounds
Color
Fonts/Text
Decorative effects
Transitions/Animations
Other
```

2017-03-20 22:34 UTC, melanierichards commented on custom-props/index.html
> +                <svg id="container" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1300 750" preserveAspectRatio="xMaxYMin"><g id="lightsource"><circle r="
What do you think about adding some preceding spaces to lines in this code so that the colon lines up from row to row?

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +    color: white;
Change all instances of this to `color: #fff;` (just a code style thing)

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +    background: #eee;
Let's just keep the page background white

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +svg#container
Does this need the tag in the selector?

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +    margin: 10px auto;
Feels a little bit squishy, can we make `margin: 2em auto;` instead?

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +    width: 70%;
70% feels pretty narrow, and this doesn't align too well with the header on the top of the page. That header has:

```
padding: 0 1.25em;
max-width: 1600px;
```

Let's do the same for the demo content, and you can make the max width smaller as you prefer (like 1200px or something). That way it aligns with the header most of the time.

2017-03-20 22:34 UTC, melanierichards commented on custom-props/index.html
> +                <svg id="container" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1300 750" preserveAspectRatio="xMaxYMin"><g id="lightsource"><circle r="
All these subheads should be a heading element instead of a paragraph element, and then you can remove the role. I also think they need a larger top margin to separate them from the content above.

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +    color: #666;
Make #000 instead

2017-03-20 22:34 UTC, melanierichards commented on custom-props/styles/demo.css
> +    font-family: 'Segoe UI', sans-serif;
Because you're not loading the default stylesheet in this demo, you'll need to add CSS for the fonts:

```
@font-face {
	font-family: base;
	src: local("Segoe UI Light"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/light/latest.woff2") format("woff2"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/light/latest.woff") format("woff");
	font-weight: 200;
}

@font-face {
	font-family: base;
	src: local("Segoe UI Semilight"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/semilight/latest.woff2") format("woff2"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/semilight/latest.woff") format("woff");
	font-weight: 300;
}

@font-face {
	font-family: base;
	src: local("Segoe UI"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff2") format("woff2"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff") format("woff");
	font-weight: 400;
}

@font-face {
	font-family: base;
	src: local("Segoe UI Semibold"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.woff2") format("woff2"),
	     url("https://c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.woff") format("woff");
	font-weight: 600;
}
```

or instead go w/ a more robust system font stack

2017-03-20 22:34 UTC, melanierichards commented on custom-props/index.html
> +                <svg id="container" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1300 750" preserveAspectRatio="xMaxYMin"><g id="lightsource"><circle r="
Perhaps explain interpolation for those not in the know?

2017-03-20 22:44 UTC, dstorey commented on custom-props/index.html
> +        <section id="wrapper" role="presentation">
Might be missing the context here, but why is there a bunch of re-assigning the role of sections, aside, header, etc? If you're removing the role by using presentation, shouldn't they just use DIV and make the code more compact? I'm not sure there is any benefit on using the sectioning elements if the semantics are removed.

I think I understand the one where you use role="image", if it is fixing up a11y in Edge for SVG, although it could be div role="image". 

If there is a reason to use the sectioning elements, then role="none" is more compact. The demo won't work on old -IE and browsers that don't support role="none" anyway so don't get the benefit of the more widely supported role="presentation".

2017-03-20 23:03 UTC, ststimac commented
Can confirm the changed code text color should be black. I think I mentioned that last week that the white on light brown doesn't meet accessibility requirements.

2017-03-21 00:46 UTC, gregwhitworth commented on custom-props/index.html
> +                <svg id="container" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1300 750" preserveAspectRatio="xMaxYMin"><g id="lightsource"><circle r="
What are you referring to here?

2017-03-21 00:51 UTC, gregwhitworth commented on custom-props/styles/demo.css
> +svg#container
No it doesn't but I like knowing it's SVG, removed it none-the-less as I don't really care.

2017-03-21 00:54 UTC, gregwhitworth commented on custom-props/index.html
> +        <section id="wrapper" role="presentation">
Not sure why my emailed version didn't show up here. But semantics go beyond a11y, although that's a large part. I'm aware that I could have used a div but then I end up in div soup and I'd prefer to see the section, article, etc.

2017-03-21 01:06 UTC, gregwhitworth commented on custom-props/index.html
> +                <svg id="container" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1300 750" preserveAspectRatio="xMaxYMin"><g id="lightsource"><circle r="
This is covered in the blog post

2017-03-21 01:31 UTC, gregwhitworth commented
@melanierichards @dstorey Regarding this statement:

> For a11y reasons I think we need to have some kind of control that will allow the person to pause all the animations in the SVG.

I don't think the dogs tail moves far enough or is large enough to cause reactions to vestibular disorder, I assume that's what you're referring to when saying "for a11y reason." That said, we could potentially mix up the animation of the tail a bit so that it isn't as constant. Like, wag->wag, delay, wag->wag->wag etc. If we feel we must have a control to turn off animations, does this cover all animations including transitions? Finally, if we go that route where would you like it placed?

2017-03-21 01:34 UTC, gregwhitworth commented
@molant I haven't had a chance to test this on an internal build since I got the feedback after leaving work. Just in the off chance it's signed off on before tomorrow (21) please don't merge this until I get a chance to ensure it works well.

2017-03-21 21:08 UTC, melanierichards commented
@gregwhitworth regarding the question about wagging animations: I think the best route is probably a control to pause all animations (including the clouds and such). I'm thinking a text only, minimal `<button>` below the bottom right corner of the demo art that says "Pause animations". If making this update would cause us not to get the demo out in a timely fashion I'm fine with us merging this PR now and submitting another PR with that update, just let me know :]

2017-03-21 21:11 UTC, melanierichards requested changes

2017-03-21 21:11 UTC, melanierichards commented on custom-props/styles/demo.css
> +    display: block;
I don't think all these spaces are needed between rules. If we remove those I think that's the extent of my feedback, besides the comments about the animation :]

2017-03-21 22:11 UTC, gregwhitworth commented
@melanierichards @molant all feedback has been addressed. The code for the animation button could easily be pulled out and made into a component since this is something that we're wanting on all demos according to the guidelines listed above.

2017-03-21 23:01 UTC, melanierichards requested changes
We're almost done! Left a couple inline comments @gregwhitworth but I was also thinking: can the paused value of the clouds animation be the state where the clouds are not in view? It's sort of jarring when you click the button and these clouds pop into view (I assuming anyone who wants that button would probably click it before the clouds were across the image). Also when you restart the animation, the clouds start offscreen, so it seems like it would make more sense to match the paused value to that as well.

2017-03-21 23:01 UTC, melanierichards commented on custom-props/styles/demo.css
> +    font-family: 'Segoe UI Semilight', 'Segoe UI', sans-serif;
This actually needs a `font-weight: 300` on it too, otherwise it tries to load the wrong weight

2017-03-21 23:01 UTC, melanierichards commented on custom-props/styles/demo.css
> +#article-wrapper a {
Needs a `padding: 0;` on it so that the underline doesn't stick out too far

2017-03-21 23:26 UTC, gregwhitworth commented
@melanierichards alrighty - we should be good to go

2017-03-22 00:41 UTC, melanierichards approved these changes

2017-03-22 00:41 UTC, melanierichards commented
@molant we can haz merge if you're satisfied (cc @gregwhitworth)

2017-03-22 01:55 UTC, molant commented
As soon as @gregwhitworth is OK I'll merge. I think he wanted to wait for something.

2017-03-22 02:58 UTC, gregwhitworth commented
@molant I checked it out this morning - we're good to go!

2017-03-22 17:12 UTC, merged