CSS Grid Demo
MicrosoftEdge/Demos-old pull request #374
Opened 2017-10-18 16:18 UTC by gregwhitworth

This adds the CSS Grid demo with tutorial. **IT IS NOT READY** but I wanted to start getting feedback from @melanierichards & @molant while I'm working on the tutorial part. I do need to add a success banner (probably below the click count). I'll start refining it and incorporating your feedback at the same time. Thanks.

2017-10-18 16:19 UTC, gregwhitworth commented
Also @dstorey do you mind doing another glance at a11y - I haven't actually tested traversal yet I focused most of my time on the game play more than anything in this demo.

2017-10-18 17:08 UTC, molant commented
@gregwhitworth where did you got the `.mp3` files? Do they need a license somewhere?

2017-10-18 17:18 UTC, gregwhitworth commented
@molant Yeah, we should probably host them somewhere not on GitHub after reviewing the license. This is actually something we'll need to do for our variable font demo as well so if you can let me know where to place them I'd appreciate it.

2017-10-18 17:19 UTC, gregwhitworth commented
@molant to answer specifically, I have a paid account with audioblocks.

2017-10-24 17:30 UTC, melanierichards requested changes

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	padding: 10px;
This seems to be adding an odd gap at the top of the sunset area and not much else, probably should be removed

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	border: 2px solid black;
I think the page looks nicer without this border

2017-10-24 17:30 UTC, melanierichards commented on grid/index.html
> +				<button id="toggle-audio">Turn <span>on</span> sounds for successful/uncessful moves</button>
Spelling error here, also it might be a bit nicer to have this as a checkbox instead of a button

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	padding: 5px;
Make this .5em

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	margin: 2px;
Removing this line makes this style feel more Microsoft-y

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	margin: 1em;
Remove this line

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +.puzzle-game > .puzzle-game-image {
Is the direct child combinatory necessary in these selectors? If not, let's remove them.

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	color: white;
Prefer hex code instead of color keyword

2017-10-24 17:30 UTC, melanierichards commented on grid/style.css
> +	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
This line and the font-weight line are redundant to cascading styles and can safely be removed

2017-10-24 17:31 UTC, melanierichards commented
Feedback not on a per-line level:

* It might be worth changing the directory name to `css-grid`, but I don't feel super strongly about that.
* It would be nice to have the title of the game inside the sunset area, with a link (styled like a button) that jumps down to the play instructions
* Using grid for the instructions area seems like overkill, unless that's what you're still working on and it's not just going to be a tube of content
* The game tile area doesn't seem to be vertically aligning with the sunset background
* Could be nice if the active tile outline was more pronounced (4px), and we should probably adjust the z-index for active tiles so they're always sitting on top of the inactive ones.
* When the demo is in a "mobile"-ish view, let's have the text that sits in the sunset area (like the clicks count) be displayed above the game area. We can add some padding to the top of that sunset area and have the background be the purple/top endpoint of the gradient in the sunset. This will probably mean that in the source order we need the text before the game, so maybe it would make sense on the wider breakpoints to flip the demo so that the text is on the left and the game is on the right?

2017-10-30 21:58 UTC, gregwhitworth commented
@melanierichards the `.button` class has .2 on the alpha channel and so this causes the background to make the anchor text illegible. What do you want the background color to be in hex notation to make the text visible?

2017-10-30 22:00 UTC, melanierichards commented
@gregwhitworth maybe start with `.button--primary` instead. Although you might want to invert/change the colors, since it's white on blue.

2017-10-30 23:23 UTC, gregwhitworth commented
@melanierichards please take a glance I made most of your changes.

@molant I expect this to get one eslint error:

> Unexpected 'this'  no-invalid-this

We need the this context to have the element that invoked the event. We have to pass it around somehow and we decided using a constant was the easiest across methods. Any suggestions here?

2017-11-01 01:41 UTC, melanierichards requested changes
@gregwhitworth the best place to start with my comments is the one that has a screenshot in it, as that might change how you approach other comments. If my comment would be better explained with a 5 min meeting, feel free to come get me. :]

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	grid-gap: 2%;
This is applying a grid gap around the discernable content of the game area, which is making this content not horizontally align with the writeup below. So either we might need a slight rewrite of the grid, or we need to take that 2% on either side into account w/ the writeup area.

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	margin: 1em;
Let's make this `2em 0` so it aligns properly

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	max-width: 75%;
Why this max-width?

2017-11-01 01:41 UTC, melanierichards commented on css-grid/background.svg
> +<?xml version="1.0" encoding="utf-8"?>
Probably a good time to compress this SVG with something like https://github.com/svg/svgo, if we're done making changes. Online GUI: https://jakearchibald.github.io/svgomg/

2017-11-01 01:41 UTC, melanierichards commented on css-grid/index.html
> +<body class="css-grid">
I'm thinking this and the `main` class might be a little confusing now, since they're not applying grid (I think the main used to?). So we might consider taking it off.

2017-11-01 01:41 UTC, melanierichards commented on css-grid/index.html
> +				<a href="#playing-the-game" class="button button--primary">Skip to instructions on playing the game</a>
Could we make this text a little shorter? Perhaps "How to Play"?

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +.button.button--primary {
Let's give this button some more vertical margin between its neighbors. Maybe `2em 0`?

2017-11-01 01:41 UTC, melanierichards commented on css-grid/index.html
> +				<h2 id="playing-the-game">CSS Grid Resources</h2>
Semantically, I think it would make more sense for this heading to be in its own `<section>`, because it's supposed to be one heading per section at a particular heading level (so, wouldn't be a problem were it an `<h3>`. For each section we can apply a `section` class on them, so that there's more spacing given by universal styles (which seems weirdly redundant but sometimes you want the style and not the semantics of a page section)

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	grid-area: game;
This line seems like legacy?

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
You can get rid of this line

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	font-weight: normal;
Also not needed

2017-11-01 01:41 UTC, melanierichards commented on css-grid/style.css
> +	grid-template-rows: 15% 30% 45%;
![palmtree](https://user-images.githubusercontent.com/340395/32256103-521861a4-be6a-11e7-8dc8-cb6564b161b3.PNG)

The game area still doesn't seem to be lining up correctly in the vertical axis for me. I'm wondering if we do `grid-template-rows: 1fr repeat(3, [static tile height])`, and have the game be a static dimension. Let's say the board is 800px square, this would only happen at viewports of 800px+. Lower than that, we can have the board be a percentage width of the page, and just let go of the vertical alignment with the backdrop at these smaller viewports. The backdrop, in this case, can just be a nice gradient that is used for texture instead of context.

2017-11-01 16:36 UTC, gregwhitworth commented on css-grid/style.css
> +	grid-template-rows: 15% 30% 45%;
I'm curious as to why this matters, I never intended nor expected the game board to completely align with the background image.

2017-11-01 16:38 UTC, gregwhitworth commented on css-grid/style.css
> +	grid-template-rows: 15% 30% 45%;
In order to accomplish it, yes you'd need the dimensions of the board and the background container to be consistent and currently the sizing of the background image is set to fill and then in mobile is contain - we could go this route but I think the time to make it work is of very little value when the focus is the game.

2017-11-01 16:48 UTC, gregwhitworth commented on css-grid/style.css
> +	max-width: 75%;
It's a left over artifact from screwing around with dl styles earlier, removed.

2017-11-01 16:49 UTC, gregwhitworth commented on css-grid/style.css
> +	grid-area: game;
No, the wrapper is still a grid - the only grid that was removed was the grid for the blog/tut layout.

2017-11-01 17:01 UTC, gregwhitworth commented on css-grid/style.css
> +	grid-gap: 2%;
What do you mean by "write up below"?

2017-11-01 17:07 UTC, gregwhitworth commented on css-grid/index.html
> +				<h2 id="playing-the-game">CSS Grid Resources</h2>
Good catch on the section, added an additional one - I have no idea what you mean by the other stuff. Feel free to stop by and explain what you want in person.

2017-11-01 22:08 UTC, melanierichards commented on css-grid/style.css
> +	grid-template-rows: 15% 30% 45%;
I thought that was how Stephanie designed it. Personally I think it looks "off" if the game tiles have the same layers as the background it's sitting on and they're pretty close to aligning, but not quite. My preference would be that the background and tiles align, but if that isn't possible within time constraints, the second best option would be if the stripes in the background of the page are significantly different heights than the tile height. I can sketch this out if that helps.

2017-11-01 22:09 UTC, melanierichards commented on css-grid/style.css
> +	grid-gap: 2%;
`.css-grid-content` and the section below it. Just "stuff that isn't inside the puzzle wrapper".

2017-11-03 01:17 UTC, melanierichards commented
@gregwhitworth I have my changes ready but I think I'm not able to push to your repo. Would you mind granting me contributor access to your fork? Thanks!

2017-11-03 15:43 UTC, gregwhitworth commented
@melanierichards you should be good to go :)

2017-11-03 19:16 UTC, melanierichards commented
@gregwhitworth I added my new styles! They still have to have the CSS linter run over them (I guess we only got half of that set up, so @molant and I will be taking a look at that), but I did scan with Sonar and fix those issues. In any case, ready for human feedback.

2017-12-06 21:48 UTC, gregwhitworth commented
@molant Hey - when can this go live? The PR has been sitting here for quite a bit, I know @melanierichards is technically signed off even though she hasn't clicked complete. It has now been waiting for over a month - it would be really good to get this live.

2017-12-06 22:05 UTC, molant commented
@gregwhitworth travis build is failing. Can you address the issue(s). @alrra will do a review later and I'll do a final tomorrow afternoon or Friday.

2017-12-06 22:26 UTC, gregwhitworth commented
@molant thanks - as I stated in this comment: https://github.com/MicrosoftEdge/Demos/pull/374#issuecomment-340614350 I'm aware of why it's failing and refactoring it to make that one thing pass isn't worth the time for an isolated demo. As such, I pushed it and called out that it is failing. Not being able to assign this, even when it makes sense is a very strong generalization for a linter to make. Thanks for the review @alrra

2017-12-06 22:48 UTC, molant commented
And then you should use `//eslint-disable-line no-invalid-this` 😊
We can't merge code that breaks the build process because it will continue breaking and making more difficult to get accurate results in the future for other demos.

2017-12-06 22:52 UTC, alrra commented on css-grid/index.html
> +<html>
`<html lang="en-us">`

2017-12-06 22:52 UTC, alrra commented on .gitignore
> +/* Sonar stuff */
sonarwhal

2017-12-06 22:52 UTC, alrra commented on css-grid/background.svg
> +<svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1290.9 714.5"><style>.st0{fill:#ECA06F;} .st1{fill:url(#SVGID_1_);} .st2{fill:#F8D186;} .st3{fill:url(#SVGID_2_);} .st4{fill:url(#SVG
This can be even smaller, namely:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1290.9 714.5"><linearGradient id="a" x1="-1506.05" x2="-1083.04" y1="1122" y2="1122" gradientTransform="rotate(-90 -767.09 -307.91)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#C5814D"/><stop offset=".11" stop-color="#C77B4D"/><stop offset=".24" stop-color="#CE6C4E"/><stop offset=".33" stop-color="#D35E4E"/><stop offset="1" stop-color="#473F87"/></linearGradient><path fill="url(#a)" d="M1325.8 0v358.1H-.1V0z"/><linearGradient id="b" x1="662.83" x2="662.83" y1="357.13" y2="580.71" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#B74E4B"/><stop offset=".49" stop-color="#8F5473"/><stop offset="1" stop-color="#615AA1"/></linearGradient><path fill="url(#b)" d="M-.1 358.1h1325.9v230H-.1z"/><path fill="#eca06f" d="M0 566h1325.8v148.5H0z"/></svg>
```

2017-12-06 22:52 UTC, alrra commented on css-grid/index.html
> +				<img tabindex=0 id="piece-1" src="grid_1.png" class="puzzle-game-image" aria-label="The" />
These images can be further optimized.

2017-12-06 22:52 UTC, alrra commented on css-grid/grid_game_extra_palm.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="240.6" height="241.4" viewBox="0 0 240.6 241.4"><path fill="#323A75" d="M95.4 21.6L18.9 32.4C8.8 33.8 1.2 42 0 51.8c-.3 2.9 2.1 5.3 5 4.9l4.2-.6c.9-.1 1
This can be even smaller, namely:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="240.6" height="241.4"><path fill="#323a75" d="M95.4 21.6L18.9 32.4A22.3 22.3 0 0 0 0 51.8a4.4 4.4 0 0 0 5 4.9l4.2-.6a4 4 0 0 0 2.4-1.2l4.7-4.4a4.3 4.3 0 0 1 5-.7l5.7 2.9c.8.4 1.7.6 2.6.4a4 4 0 0 0 2.4-1.2l4.7-4.4a4.3 4.3 0 0 1 5-.7l5.7 2.9c.8.4 1.7.6 2.6.4a4 4 0 0 0 2.4-1.2l4.7-4.4a4.3 4.3 0 0 1 5-.7l5.7 2.9c.8.4 1.7.6 2.6.4a4 4 0 0 0 2.4-1.2l4.7-4.4a4.3 4.3 0 0 1 5-.7l5.7 2.9c.8.4 1.7.6 2.6.4a4 4 0 0 0 2.4-1.2L98 39a4.3 4.3 0 0 1 5-.7l5.7 2.9c.8.4 1.7.6 2.6.4l4.2-.6a4.3 4.3 0 0 0 3.4-6.1 22 22 0 0 0-23.5-13.3zm49.7-.6l76.5 10.8a22.2 22.2 0 0 1 18.9 19.4 4.4 4.4 0 0 1-5 4.9l-4.2-.6a4 4 0 0 1-2.4-1.2l-4.7-4.4a4.3 4.3 0 0 0-5-.7l-5.7 2.9c-.8.4-1.7.6-2.6.4a4 4 0 0 1-2.4-1.2l-4.7-4.4a4.3 4.3 0 0 0-5-.7l-5.7 2.9c-.8.4-1.7.6-2.6.4a4 4 0 0 1-2.4-1.2l-4.7-4.4a4.3 4.3 0 0 0-5-.7l-5.7 2.9c-.8.4-1.7.6-2.6.4a4 4 0 0 1-2.4-1.2l-4.7-4.4a4.3 4.3 0 0 0-5-.7l-5.7 2.9c-.8.4-1.7.6-2.6.4a4 4 0 0 1-2.4-1.2l-4.7-4.4a4.3 4.3 0 0 0-5-.7l-5.7 2.9c-.8.4-1.7.6-2.6.4l-4.2-.6a4.3 4.3 0 0 1-3.4-6.1A22.5 22.5 0 0 1 145.1 21z"/><path fill="#323a75" d="M143.6 36.3c1-.4 1.9-1.1 2.4-2l1.3-2a5.3 5.3 0 0 1 5.6-2.2l2.3.6c1 .3 2.1.2 3.1-.2s1.9-1.1 2.4-2l1.3-2a5.3 5.3 0 0 1 5.6-2.2l2.3.6c1 .3 2.1.2 3.1-.2s1.9-1.1 2.4-2l1.3-2a5.3 5.3 0 0 1 5.6-2.2l2.3.6c1 .3 2.1.2 3.1-.2s1.9-1.1 2.4-2l1.3-2a5.3 5.3 0 0 1 5.6-2.2l2.3.6c1 .3 2.1.2 3.1-.2l.6-.2a5.2 5.2 0 0 0 1.6-8.7A17 17 0 0 0 187 .9l-55 21.8A17 17 0 0 0 121.3 37a5.2 5.2 0 0 0 7.1 5.3l.6-.2c1-.4 1.9-1.1 2.4-2l1.3-2a5.3 5.3 0 0 1 5.6-2.2l2.3.6c.9.3 2 .2 3-.2zm-46.7 0c-1-.4-1.9-1.1-2.4-2l-1.3-2a5.3 5.3 0 0 0-5.6-2.2l-2.3.6c-1 .3-2.1.2-3.1-.2s-1.9-1.1-2.4-2l-1.3-2a5.3 5.3 0 0 0-5.6-2.2l-2.3.7c-1 .3-2.1.2-3.1-.2s-1.9-1.1-2.4-2l-1.3-2a5.3 5.3 0 0 0-5.6-2.2l-2.3.6c-1 .3-2.1.2-3.1-.2s-1.9-1.1-2.4-2l-1.3-2a5.3 5.3 0 0 0-5.6-2.2l-2.3.6c-1 .3-2.1.2-3.1-.2l-.6-.2a5.2 5.2 0 0 1-1.6-8.7A17 17 0 0 1 53.5 1l55.1 21.6a17 17 0 0 1 10.7 14.3 5.2 5.2 0 0 1-7.1 5.3l-.6-.2c-1-.4-1.9-1.1-2.4-2l-1.3-2a5.3 5.3 0 0 0-5.6-2.2l-2.3.6c-1 .4-2.1.3-3.1-.1z"/><g fill="#323a75"><path d="M119.7 46.5a7.7 7.7 0 0 0-6.3 3.4c-5.4 8.4-18.3 32.3-19.9 73.7-1.7 43.9 16.3 91.3 22.4 106a7.5 7.5 0 0 0 6.9 4.6H141c4.2 0 6.8-4.4 4.8-8.1-10-18.5-33.2-64.6-34-96.4-.8-33.1 8.4-59 14.7-72.6a7.5 7.5 0 0 0-6.8-10.6z"/><path d="M141 234.6h-18.2c-3.2 0-6-1.9-7.2-4.8-5.7-13.7-24.1-61.9-22.4-106.1 1.6-41.5 14.5-65.5 20-73.9a7.9 7.9 0 0 1 13.2 0 8 8 0 0 1 .5 7.5 167 167 0 0 0-14.7 72.5c.8 31.7 24 77.9 34 96.3 1 1.8.9 4-.1 5.8a6.2 6.2 0 0 1-5.1 2.7zM119.7 46.9a7.2 7.2 0 0 0-6 3.2c-5.4 8.3-18.3 32.2-19.8 73.5-1.7 44.1 16.7 92.2 22.3 105.8a7 7 0 0 0 6.6 4.4H141a5.2 5.2 0 0 0 4.5-7.6c-10-18.4-33.3-64.7-34.1-96.6-.8-33.7 8.9-60.1 14.7-72.8 1-2.2.8-4.7-.5-6.8a7 7 0 0 0-5.9-3.1z"/></g><ellipse cx="132.6" cy="229.1" fill="#eca06f" rx="65.7" ry="12.2"/></svg>
```

2017-12-06 22:52 UTC, alrra commented on css-grid/grid.js
> +            (rowOfCurrentPiece === rowOfHiddenPiece && Math.abs(colOfHiddenPiece - colOfCurrentPiece) === 1)
Wrong indent.

2017-12-06 22:52 UTC, alrra commented on css-grid/index.html
> +				<img tabindex=0 id="piece-1" src="grid_1.png" class="puzzle-game-image" aria-label="The" />
Ending `/` is not needed.

2017-12-06 22:59 UTC, alrra commented
> We can't merge code that breaks the build process because it will continue breaking and making more difficult to get accurate results in the future for other demos.

I took care of that.

2017-12-06 23:11 UTC, alrra commented on .gitignore
> +/* sonarwhal */
@molant I'm going to remove these since we don't have `sonarwhal` integrated yet.

2017-12-06 23:24 UTC, molant requested changes
Couple comments:
- If this demo uses custom styles, we need the `config.json` file with:

```json
{
   "isHTML": true
}
```
- There's a `package-lock.json` that needs to be removed
- We need to say where the `failure.wav` file comes from. Even if it doesn't need a license, we should say where we got it. You can add this in a LICENSES.txt file for example

@melanierichards if all your feedback has been addressed can you change the status of your review?

2017-12-06 23:28 UTC, alrra commented
> config.json file 

Added it.

2017-12-06 23:33 UTC, alrra commented
> There's a package-lock.json that needs to be removed

The `package-lock.json` is where it's supposed to be.

2017-12-07 00:12 UTC, closed without merging

2017-12-07 18:13 UTC, alrra commented on css-grid/index.html
> +				<img tabindex=0 id="piece-1" src="grid_1.png" class="puzzle-game-image" aria-label="The">
@gregwhitworth Don't these images need an `alt` attribute or at least `role="presentation"`?

Cc: @dstorey

2017-12-07 18:19 UTC, gregwhitworth commented on css-grid/index.html
> +				<img tabindex=0 id="piece-1" src="grid_1.png" class="puzzle-game-image" aria-label="The">
No, as you'll notice they have an aria label and thus this is what is read out, I definitely don't want role=presentation as that's definitely not what they are.

2017-12-07 18:23 UTC, alrra commented on css-grid/index.html
> +				<img tabindex=0 id="piece-1" src="grid_1.png" class="puzzle-game-image" aria-label="The">
> as you'll notice they have an aria label and thus this is what is read out, 

Ok.